pipeline {
    agent any 
    stages {
        
        stage('Build') {
            bat "mvn clean install -DskipTests"
        }

        stage('Copy File') { 
            bat "copy .\\target\\restapi-0.0.1-SNAPSHOT.jar E:\\restapi.jar"
        }
    }
}