node {
    def remote = [:]
    remote.name = 'dev'
    remote.host = '10.96.23.230'
    remote.port = 22
    remote.allowAnyHosts = true
    remote.user = 'ocboper'
    remote.password = 'Qwert!2345'

    stage('Build') {
        dir("restapi") {
            bat "mvn clean install -Dmaven.test.skip=true"
        }
    }

    stage('Copy other location') { 
        bat "copy .\\restapi\\target\\restapi-0.0.1-SNAPSHOT.jar E:\\restapi.jar"
    }

    stage('Copy to server') {
        sshCommand remote: remote, command: "lsb_release -a"
        dir('.\\restapi\\target') {
            sshPut remote: remote, from: 'restapi-0.0.1-SNAPSHOT.jar', into: '/home/ocboper/jenskin'
        }
    }
}