pipeline {
    agent any 
    stages {

        stage('Pull git') {
            git branch: "master", url: 'https://github.com/lhvan0106/lhvan0106_jenkins.git'
        }
        
        stage('Build') {
            bat "mvn clean install -DskipTests"
        }

        stage('Copy File') { 
            bat "copy .\\target\\restapi-0.0.1-SNAPSHOT.jar E:\\restapi.jar"
        }
    }
}